language: python
python:
- 2.7
- 3.5
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: KoBmesLGd4zLN4pHU5PWNYET/S2JdfMC5ko97Ko1LZlhAs/kIiwoHheJPyFxnUF0i0XxqoX82ifxnT3gtXanPo+ouJv6LTgPO3lAnL8LIrs7840cEvu7GpWsTVsxkdKeLVfSpmDFQH6LXF9RwCQXQDT1C8kBDiCz26ynZppPH83JcqYe/JM64XrSkZnn3AJbp5LljVg7hq0YyV7CVg7lFkfgBBeQ9jAJibg3va6V4ussyZoJg6T0v7lStYoI74+MmcbG9Lga4NJG/FWIfPXIbwf2NLJr2aE+TdQbM4RXDaNNq41BDjszBkSaPwQTHHKAJAkR56UlfFPq+SVrxPBj0cQDXwVc6Zw8uG80ahhd34gydFcvGuQNz7EE5VO5rp/MryEGKl2IRoLBYBsgWJZgbs9uAUjM86eqaVIJs2X4ewSOsXTSXY3IuGsp8ru+1CrNHON/SNuLzeMR+WFQhUaAnmxGuWEf10JGiJ2ZeZXnBDYwkvJfhFKyhXa8L4NoKVtTWfh+zrf6rioDeFBXxUvqupPAj/wcKteAIaNOesWO941WZ4fVmh9fIO9xtEh9IUSo4b1Ct4bQtQx13A4szXMU8VO8eb7AY4nNWVYXa125HXS2Ysj0T1jvqyC6lpv9ZCQOTWHZFdyEQ9o9okwbOjcIHgmTI5sy9k207vtORD/o4zY=
  on:
    tags: true
    repo: cdumay/json-sort
